# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'flexApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flexApp
pod 'FlexLayout'
pod 'SnapKit', '~> 5.0.1'
pod 'LookinServer', :configurations => ['Debug']


  target 'flexAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flexAppUITests' do
    # Pods for testing
  end

end
