# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'



def demoApp_pods

  #pod 'AFNetworking', '~> 4.0.1'
  pod 'LookinServer', :configurations => ['Debug']

 
    pod 'FCKTable', :path => 'Pods/FCKTable'
 
    pod 'FCKTableView', :path => 'Pods/FCKTableView'
end


inhibit_all_warnings!
target 'DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

demoApp_pods

end
